spring:
  datasource:
    url: jdbc:mysql://localhost/exitus
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update

    generate-ddl: true
    open-in-view: false

server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET:3x1Tu515tH3b3st}